#!/usr/local/bin/python
import pprint
import logging

template_sty_name = "ipynb-tex-template.sty"
python_source_name = "export_cells.py"
output_sty_name = "ipynb-tex.sty"

template_sty_source_lines = open(template_sty_name, "r").readlines()
template_sty_source = ''.join(template_sty_source_lines)
python_source_lines = open(python_source_name, "r").readlines()
python_source = ''.join(python_source_lines)
updated_sty_source = template_sty_source.replace('#input#', python_source)
open(output_sty_name, "w").write(updated_sty_source)
